### ISSUE TITLE
Roadmap for hooks

### ISSUE THREAD

**Issue by stereobooster** [contiamo/restful-react#101]
**Is your feature request related to a problem? Please describe.**
Implement hooks version of restful-react

**Describe the solution you'd like**
This is umbrella ticket for hooks. @fabien0102 let's write down what we need to get hooks version.

**Describe alternatives you've considered**
N/A

**Additional context**
Previous attempt https://github.com/contiamo/restful-react/pull/79/files

**Comment by fabien0102** [comment]
My todo for the Get hooks:

 - [ ] Update react & react-dom
 - [ ] Fix the unit tests
 - [ ] Implement the debounce
 - [ ] Deal with trailing slash
 - [ ] Add some documentation
 - [ ] Add a `--hooks` flag to the openAPI generator 🤘

**Comment by TejasQ** [comment]
@fabien0102 @stereobooster let's invite the OSS community to participate!

https://twitter.com/TejasKumar_/status/1095328365148397569

**Comment by fabien0102** [comment]
@TejasQ Not sure about the status/need for `usePool` anymore 😕 

It's actually quite easy to implement with hooks in a userland:

A little concrete example from our internal product, poll if the status finish by `ing` ("waiting", "finishing", …)
```tsx
const [isPolling, setIsPolling] = useState(false);
// Poll data if we have `*ing` in status
useEffect(() => {
  if (response && response.data.filter(i => i.status.match(/ing$/)).length > 0) {
    setIsPolling(true);
    const timerId = window.setTimeout(() => {
      setIsPolling(false);
      refetch();
    }, 1000);
    return () => {
      window.clearTimeout(timerId);
      setIsPolling(false);
    };
  }
  return;
}, [response, refetch, setIsPolling]);
```

This can be easily tweak to fit any usecases, it's actually very flexible!

**Comment by TejasQ** [comment]
Let's not support it for now and revisit it when/if the need arises.
